//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALU_ERP.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        public articulo()
        {
            this.linea_pedido_c = new HashSet<linea_pedido_c>();
            this.linea_pedido_p = new HashSet<linea_pedido_p>();
        }
    
        public string idArt { get; set; }
        public string Nombre { get; set; }
        public Nullable<float> Peso { get; set; }
        public string Tipo { get; set; }
        public int Estado { get; set; }
        public float Precio { get; set; }
        public float IVA { get; set; }
        public string Descripcion { get; set; }
        public string Origen { get; set; }
        public string Imagen { get; set; }
    
        public virtual estado estado1 { get; set; }
        public virtual ICollection<linea_pedido_c> linea_pedido_c { get; set; }
        public virtual ICollection<linea_pedido_p> linea_pedido_p { get; set; }
    }
}
