//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALU_ERP.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacto
    {
        public int idCONTACTO { get; set; }
        public string Nombre { get; set; }
        public string Origen { get; set; }
        public string Producto { get; set; }
    }
}
