//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALU_ERP.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado
    {
        public estado()
        {
            this.articuloes = new HashSet<articulo>();
            this.clientes = new HashSet<cliente>();
            this.proveedors = new HashSet<proveedor>();
        }
    
        public int idESTADOS { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<articulo> articuloes { get; set; }
        public virtual ICollection<cliente> clientes { get; set; }
        public virtual ICollection<proveedor> proveedors { get; set; }
    }
}
