//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALU_ERP.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public factura()
        {
            this.linea_factura = new HashSet<linea_factura>();
        }
    
        public int Numero { get; set; }
        public int Empresa { get; set; }
        public int Facturado { get; set; }
        public int Enviado { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo_ped { get; set; }
        public string Forma_pago { get; set; }
        public int Cliente { get; set; }
        public Nullable<float> Total_bruto { get; set; }
        public Nullable<float> Dto { get; set; }
        public Nullable<float> Dpp { get; set; }
        public Nullable<float> Portes { get; set; }
        public Nullable<float> IVA { get; set; }
        public Nullable<float> Re { get; set; }
        public Nullable<float> Cuota_Re { get; set; }
        public Nullable<float> Total { get; set; }
    
        public virtual ICollection<linea_factura> linea_factura { get; set; }
    }
}
