//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALU_ERP.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class linea_pedido_c
    {

        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Linea")]
        public int Linea { get; set; }


        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Num.Pedido")]
        public int Num_ped { get; set; }



        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Cantidad")]
        [Range(1, 9999, ErrorMessage = "No admite")]
        public int Cantidad { get; set; }




        public Nullable<float> Total { get; set; }




        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Cod. Artículo")]
        public string idArticulo { get; set; }




    
        public virtual articulo articulo { get; set; }
        public virtual pedido_c pedido_c { get; set; }
    }
}
