//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALU_ERP.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GaluEntities : DbContext
    {
        public GaluEntities()
            : base("name=GaluEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<albaran> albarans { get; set; }
        public virtual DbSet<articulo> articuloes { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<contacto> contactoes { get; set; }
        public virtual DbSet<empresa> empresas { get; set; }
        public virtual DbSet<estado_ped> estado_ped { get; set; }
        public virtual DbSet<estado> estados { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<forma_pago> forma_pago { get; set; }
        public virtual DbSet<iva> ivas { get; set; }
        public virtual DbSet<linea_factura> linea_factura { get; set; }
        public virtual DbSet<linea_pedido_c> linea_pedido_c { get; set; }
        public virtual DbSet<linea_pedido_p> linea_pedido_p { get; set; }
        public virtual DbSet<pedido_c> pedido_c { get; set; }
        public virtual DbSet<pedido_p> pedido_p { get; set; }
        public virtual DbSet<proveedor> proveedors { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tarifa> tarifas { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
