//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALU_ERP.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Validations;

    public partial class proveedor
    {
        public proveedor()
        {
            this.pedido_p = new HashSet<pedido_p>();
        }


        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Código")]
        public int idProv { get; set; }


        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Razón Social")]
        public string RazonSocial { get; set; }


        [NIF(ErrorMessage = "El NIF es incorrecto")]
        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "NIF")]
        public string NIF { get; set; }


        [NIF(ErrorMessage = "El NIF es incorrecto")]
        [Display(Name = "NIF_R")]
        public string NIF_R { get; set; }


        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Domicilio")]
        public string Domicilio { get; set; }


        [CP(ErrorMessage = "El código postal")]
        [Display(Name = "CP")]
        [StringLength(5)]
        public string CP { get; set; }


        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Población")]
        public string Poblacion { get; set; }


        [Display(Name = "Provincia")]
        public string Provincia { get; set; }



        [Display(Name = "País")]
        public string Pais { get; set; }


        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Teléfono")]
        // [DataType(DataType.PhoneNumber)]
        [Phone(ErrorMessage = "Número incorrecto")]
        public string Telefono { get; set; }


        [Display(Name = "Mail")]
        // [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Mail incorrecto")]
        public string Mail { get; set; }


        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Fecha Alta")]
        public System.DateTime Fecha_A { get; set; }


        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Estado")]
        public int Estado { get; set; }


        [Display(Name = "Imagen")]
        public string Imagen { get; set; }



        public virtual estado estado1 { get; set; }



        public virtual ICollection<pedido_p> pedido_p { get; set; }
    }
}
