//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALU_ERP.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Validations;
    
    public partial class proveedor
    {
        public proveedor()
        {
            this.pedido_p = new HashSet<pedido_p>();
        }
    
        public int idProv { get; set; }
        public string RazonSocial { get; set; }
        public string NIF { get; set; }
        public string NIF_R { get; set; }
        public string Domicilio { get; set; }
        public string CP { get; set; }
        public string Poblacion { get; set; }
        public string Provincia { get; set; }
        public string Pais { get; set; }
        public string Telefono { get; set; }
        public string Mail { get; set; }
        public System.DateTime Fecha_A { get; set; }
        public int Estado { get; set; }
        public string Imagen { get; set; }
    
        public virtual estado estado1 { get; set; }
        public virtual ICollection<pedido_p> pedido_p { get; set; }
    }
}
