//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALU_ERP.Entidades
{
    using System;
    using System.Collections.Generic;
    using GALU_ERP.Models.User;

    public partial class usuario
    {
        public long id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public long Rol { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }

        public virtual role role { get; set; }


        public usuario(UserModel model)
        {

            Nombre = model.Nombre;
            Apellidos = model.apellidos;
            Email = model.email;
            UserName = model.userName;
            Password = model.Password;
            Telefono = model.telefono;
            Rol = 1;


        }



    }
}
